# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yyean-wa < yyean-wa@student.42kl.edu.my    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/01/11 18:37:56 by yyean-wa          #+#    #+#              #
#    Updated: 2025/01/11 19:18:47 by yyean-wa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	g++ *.cpp -Wall -Wextra -Werror -std=c++98 -o zombie_horde -pedantic

clean:
	rm zombie_horde
