# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: yyean-wa < yyean-wa@student.42kl.edu.my    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/02 21:12:46 by yyean-wa          #+#    #+#              #
#    Updated: 2025/03/04 02:57:10 by yyean-wa         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	c++ *.cpp -Wall -Wextra -Werror -std=c++98 -o brain -pedantic

clean:
	rm brain

# valgrind --leak-check=full --show-leak-kinds=all ./brain
